[package]
name = "untitled_rust_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
log = "0.4.20"
itertools = "0.12.1"
thiserror = "1.0.57"
anyhow = "1.0.80"
lazy_static = "1.4.0"
regex = { version = "1.10.3", optional = true }
reqwest = { version = "0.11.24", features = ["blocking"], optional = true }
http = { version = "1.0.0", optional = true }
linkify = { version = "0.10.0", optional = true }
lopdf = { version = "0.32.0", optional = true}
pdf = { version = "0.9.0", optional = true}
pdf-extract = { version = "0.7.4", optional = true }

[features]
default = ["pdf", "link_extraction"]
link_extraction = ["dep:linkify"]
regex_extraction = ["dep:regex"]
pdf = ["dep:lopdf", "dep:pdf", "dep:pdf-extract"]
websites = ["dep:reqwest", "dep:http"]
