[package]
name = "untitled_rust_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
log = "0.4.21"
itertools = "0.12.1"
thiserror = "1.0.58"
anyhow = "1.0.81"
lazy_static = "1.4.0"
regex = { version = "1.10.4", optional = true }
reqwest = { version = "0.12.2", features = ["blocking"], optional = true }
http = { version = "1.0.0", optional = true }
linkify = { version = "0.10.0", optional = true }
mupdf = { version = "0.4.2", optional = true }
zip = { version = "0.6.6", optional = true }
xml-rs = { version = "0.8.19", optional = true }

[features]
default = ["pdf", "link_extraction"]
link_extraction = ["dep:linkify"]
regex_extraction = ["dep:regex"]
pdf = ["dep:mupdf"]
websites = ["dep:reqwest", "dep:http"]
raw_text = []
ooxml = ["dep:xml-rs", "dep:zip"]

