[package]
name = "link_scraper"
version = "0.1.0"
edition = "2021"
exclude = ["test_files/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.13.0" # MIT or Apache-2.0
thiserror = "1.0.58" # MIT or Apache-2.0
linkify = { version = "0.10.0"} # MIT or Apache-2.0
mupdf = { version = "0.4.2", optional = true } # AGPL-3.0
zip = { version = "2.1.3", optional = true } # MIT
xml-rs = { version = "0.8.20", optional = true } # MIT
rtf-parser = { version = "0.3.0", optional = true } # MIT
infer = { version = "0.16.0", optional = true } # MIT
kamadak-exif = { version = "0.5.5", optional = true} # BSD-2-Clause

#  Other crate-licenses:
#  ✓ Apache-2.0 OR MIT: aes, arbitrary, bitflags, bitflags, block-buffer, bumpalo, bzip2, bzip2-sys, cc, cexpr, cfg-if, cipher, const-cstr, core-foundation, core-foundation-sys, core-graphics, core-graphics-types, core-text, cpufeatures, crc, crc-catalog, crc32fast, crossbeam-utils, crypto-common, deranged, derivative, derive_arbitrary, digest, dirs-next, dirs-sys-next, displaydoc, either, equivalent, flate2, float-ord, fnv, font-kit, foreign-types, foreign-types-shared, freetype, getrandom, glob, hashbrown, hmac, indexmap, inout, itertools, jobserver, lazy_static, lazycell, libc, linkify, log, minimal-lexical, num-conv, once_cell, pathfinder_geometry, pathfinder_simd, pbkdf2, peeking_take_while, pkg-config, powerfmt, ppv-lite86, proc-macro-crate, proc-macro2, quote, rand, rand_chacha, rand_core, regex, regex-automata, regex-syntax, rustc-hash, rustc_version, semver, serde, serde_derive, sha1, shlex, syn, syn, thiserror, thiserror-impl, time, time-core, toml_datetime, toml_edit, typenum, uuid, version_check, winapi, winapi-i686-pc-windows-gnu, winapi-x86_64-pc-windows-gnu, windows-targets, windows_aarch64_gnullvm, windows_aarch64_msvc, windows_i686_gnu, windows_i686_msvc, windows_x86_64_gnu, windows_x86_64_gnullvm, windows_x86_64_msvc, wio, zeroize, zeroize_derive, zstd-safe, zstd-sys
#  ✓ Apache-2.0 OR MIT OR Zlib: miniz_oxide
#  ✓ BSD-2-Clause: kamadak-exif, mutate_once
#  ✓ BSD-3-Clause: bindgen, subtle
#  ✓ BSL-1.0: lockfree-object-pool
#  ✓ ISC: libloading
#  ✓ MIT: cfb, deflate64, dlib, freetype-sys, generic-array, infer, libredox, lzma-rs, nom, redox_syscall, redox_users, rtf-parser, simd-adler32, winnow, xml-rs, yeslogic-fontconfig-sys, zip, zstd
#  ✓ MIT OR Unlicense: aho-corasick, byteorder, memchr, same-file, walkdir, winapi-util
#  ~ AGPL-3.0: mupdf (I think this is fine as long as I did not modify the code itself. But I'm also no lawyer and if 'modifiing' also includes using the code for my own crate the this is probably bad and my crate needs to use this license as well.)
#  ~ MPL-2.0: dwrote (So theoretically this is pretty restrictive in terms of redistribution, but also I cannot find the reason this crate is even in this list. I don't seem to be using it at all....maybe its just a problem with cargo license?)


[features]
default = ["any_format", "text_file"]
text_file = []
pdf = ["dep:mupdf"]
xml = ["dep:xml-rs"]
xlink = ["dep:xml-rs"]
svg = ["xml"]
ooxml = ["dep:xml-rs", "dep:zip"]
odf = ["dep:xml-rs", "dep:zip"]
rtf = ["dep:rtf-parser"]
image = ["dep:kamadak-exif"]
any_format = ["dep:infer"]

