[package]
name = "untitled_rust_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding_rs = "0.8.33"
http = "1.0.0"
reqwest = { version = "0.11.24", features = ["blocking"] }
regex = "1.10.3"
log = "0.4.20"
itertools = "0.12.1"
lopdf = "0.32.0"
thiserror = "1.0.57"
anyhow = "1.0.80"
lazy_static = "1.4.0"
